-- MySQL Script generated by MySQL Workbench
-- 09/27/16 14:14:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema InstantTutor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InstantTutor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InstantTutor` DEFAULT CHARACTER SET utf8 ;
USE `InstantTutor` ;

-- -----------------------------------------------------
-- Table `InstantTutor`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersername` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `zipcode` CHAR(5) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`tutors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tutor_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`student_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`student_subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_subject_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`tutor_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`tutor_ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tutor_id` INT NOT NULL,
  `level` TINYINT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_rating_users1_idx` (`user_id` ASC),
  INDEX `fk_tutor_rating_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_tutor_rating_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor_rating_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `InstantTutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`student_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`student_ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `tutor_id` INT NOT NULL,
  `level` TINYINT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_users_idx` (`user_id` ASC),
  INDEX `fk_student_rating_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_rating_users0`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_rating_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `InstantTutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`tutor_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`tutor_subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tutor_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_subject_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_tutor_subject_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `InstantTutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`chatrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`chatrooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `chatroom_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_chatroom1_idx` (`chatroom_id` ASC),
  CONSTRAINT `fk_messages_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `InstantTutor`.`chatrooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`chatrooms_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`chatrooms_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `chatroom_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatroom_user_users1_idx` (`user_id` ASC),
  INDEX `fk_chatroom_user_chatroom1_idx` (`chatroom_id` ASC),
  CONSTRAINT `fk_chatroom_user_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chatroom_user_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `InstantTutor`.`chatrooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`skype_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`skype_appointments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `createed_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`sac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`sac` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `skype_appointment_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sac_users1_idx` (`user_id` ASC),
  INDEX `fk_sac_skype_appointments1_idx` (`skype_appointment_id` ASC),
  CONSTRAINT `fk_sac_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sac_skype_appointments1`
    FOREIGN KEY (`skype_appointment_id`)
    REFERENCES `InstantTutor`.`skype_appointments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`travel_appointmets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`travel_appointmets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstantTutor`.`tac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstantTutor`.`tac` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `travel_appointmet_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tac_users1_idx` (`user_id` ASC),
  INDEX `fk_tac_travel_appointmets1_idx` (`travel_appointmet_id` ASC),
  CONSTRAINT `fk_tac_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `InstantTutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tac_travel_appointmets1`
    FOREIGN KEY (`travel_appointmet_id`)
    REFERENCES `InstantTutor`.`travel_appointmets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
