-- MySQL Script generated by MySQL Workbench
-- 09/28/16 18:51:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema instanttutor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instanttutor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instanttutor` DEFAULT CHARACTER SET utf8 ;
USE `instanttutor` ;

-- -----------------------------------------------------
-- Table `instanttutor`.`chatrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`chatrooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usersername` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `pic_url` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`chatrooms_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`chatrooms_users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `chatroom_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatroom_user_users1_idx` (`user_id` ASC),
  INDEX `fk_chatroom_user_chatroom1_idx` (`chatroom_id` ASC),
  CONSTRAINT `fk_chatroom_user_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chatroom_user_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `instanttutor`.`chatrooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `chatroom_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_chatroom1_idx` (`chatroom_id` ASC),
  INDEX `fk_messages_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_messages_chatroom1`
    FOREIGN KEY (`chatroom_id`)
    REFERENCES `instanttutor`.`chatrooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`zipcodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`zipcodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zipcode` CHAR(5) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_zipcode_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_zipcode_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instanttutor`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `udateed_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instanttutor`.`streets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`streets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instanttutor`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`cities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instanttutor`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `zipcode_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `street_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_zipcode1_idx` (`zipcode_id` ASC),
  INDEX `fk_address_state1_idx` (`state_id` ASC),
  INDEX `fk_address_street1_idx` (`street_id` ASC),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_zipcode1`
    FOREIGN KEY (`zipcode_id`)
    REFERENCES `instanttutor`.`zipcodes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `instanttutor`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_street1`
    FOREIGN KEY (`street_id`)
    REFERENCES `instanttutor`.`streets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `instanttutor`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instanttutor`.`skype_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`skype_appointments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL DEFAULT NULL,
  `createed_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  `address_street_id` INT NOT NULL,
  `address_city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_skype_appointments_address1_idx` (`address_id` ASC, `address_street_id` ASC, `address_city_id` ASC),
  CONSTRAINT `fk_skype_appointments_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `instanttutor`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`sac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`sac` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `skype_appointment_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sac_users1_idx` (`user_id` ASC),
  INDEX `fk_sac_skype_appointments1_idx` (`skype_appointment_id` ASC),
  CONSTRAINT `fk_sac_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sac_skype_appointments1`
    FOREIGN KEY (`skype_appointment_id`)
    REFERENCES `instanttutor`.`skype_appointments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`tutors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`tutors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tutor_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`student_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`student_ratings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `tutor_id` INT(11) NOT NULL,
  `level` TINYINT(4) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rating_users_idx` (`user_id` ASC),
  INDEX `fk_student_rating_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_rating_users0`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_rating_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `instanttutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`student_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`student_subjects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subject_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_subject_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`travel_appointmets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`travel_appointmets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL DEFAULT NULL,
  `comment` TEXT NULL,
  `location` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  `address_street_id` INT NOT NULL,
  `address_city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_travel_appointmets_address1_idx` (`address_id` ASC, `address_street_id` ASC, `address_city_id` ASC),
  CONSTRAINT `fk_travel_appointmets_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `instanttutor`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`tac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`tac` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `travel_appointmet_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tac_users1_idx` (`user_id` ASC),
  INDEX `fk_tac_travel_appointmets1_idx` (`travel_appointmet_id` ASC),
  CONSTRAINT `fk_tac_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tac_travel_appointmets1`
    FOREIGN KEY (`travel_appointmet_id`)
    REFERENCES `instanttutor`.`travel_appointmets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`tutor_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`tutor_ratings` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `tutor_id` INT(11) NOT NULL,
  `level` TINYINT(4) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_rating_users1_idx` (`user_id` ASC),
  INDEX `fk_tutor_rating_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_tutor_rating_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `instanttutor`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tutor_rating_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `instanttutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `instanttutor`.`tutor_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instanttutor`.`tutor_subjects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tutor_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutor_subject_tutor1_idx` (`tutor_id` ASC),
  CONSTRAINT `fk_tutor_subject_tutor1`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `instanttutor`.`tutors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
